eval_gemfile('../common_spree_dependencies.rb')

spree_opts = { github: 'spree/spree', branch: 'SD-1426-migrate-spree-related-products' }
gem 'spree_core', spree_opts
gem 'spree_api', spree_opts

gemspec
