require 'spree_core'
require 'spree_api'

require 'sprockets/railtie'

require 'jquery-rails'
require 'jquery-ui-rails'
require 'select2-rails'
require 'flatpickr'
require 'bootstrap'
require 'glyphicons'
require 'hotwire-rails'
require 'popper_js'
require 'importmap-rails'
require 'inline_svg'
require 'responders'
require 'tinymce-rails'

require 'spree/backend/action_callbacks'
require 'spree/backend/callbacks'
require 'spree/backend/engine'
