require 'spree_core'
require 'spree_api'

require 'sprockets/railtie'

require 'jquery-rails'
require 'jquery-ui-rails'
require 'select2-rails'
require 'flatpickr'
require 'flag-icons-rails'
require 'bootstrap'
require 'glyphicons'
require 'hotwire-rails'
require 'inline_svg'
require 'jsbundling-rails'
require 'responders'
require 'tinymce-rails'
require 'wannabe_bool'

require 'spree/backend/action_callbacks'
require 'spree/backend/callbacks'
require 'spree/backend/engine'
